### ISSUE TITLE
crashes

### ISSUE THREAD

**Issue by ganna-shmatova** [dominictarr/fs-reverse#6]
Using it as a tail function for a remote file

``` javascript
var done = 0;
var data ='';
var stream = fsr(log.file);
stream.on('data', function(chunk){
    if(done < lines){
        done++;
        data = chunk + '\n' + data; //reverses lines to correct them
    }else{
        stream.destroy(); //Iffy. So stream doesn't populate buffer next time
    }
}).on('close', function(){
    response.send(200, data);
}).on('error', function(err){
    if(err) errors.fileRead(err.toString(), log.file).send(response);
});
```

```
/vm/someplace/dshfgf - wrqgfw x.log

fs.js:457
  binding.read(fd, buffer, offset, length, position, wrapper);
          ^
Error: Offset is out of bounds
    at Object.fs.read (fs.js:457:11)
    at read (/var/www/html/AdminExtension/extension/extension/node_modules/fs-reverse/index.js:43:10)
    at /var/www/html/AdminExtension/extension/extension/node_modules/fs-reverse/index.js:33:18
    at Object.oncomplete (fs.js:107:15)
Closing Node app
```

**Comment by AlexanderFillbrunn** [comment]
I get the same error when I want to read an empty file.

**Comment by ganna-shmatova** [comment]
now if someone were to merge the fix...

To make matters worse, I found out fs-reverse reads whole file to find the last lines. So I made a reader myself, that can tail/head correctly... didn't make it only a module though https://gist.github.com/ganna-shmatova/42faec34efa640d05a1f
